import type { ThemeColors, ThemeId } from "../types";

export const THEMES: ThemeColors[] = [
  {
    id: "mint",
    name: "Mint Green",
    primary: "#6EE7B7",
    primaryDark: "#10B981",
    primaryLight: "#D1FAE5",
    accent: "#34D399",
    bg: "#F0FDF4",
    surface: "#FFFFFF",
    text: "#064E3B",
    textMuted: "#6B7280",
    border: "#E5E7EB",
  },
  {
    id: "pastel",
    name: "Pastel Green",
    primary: "#A7F3D0",
    primaryDark: "#6EE7B7",
    primaryLight: "#ECFDF5",
    accent: "#5EEAD4",
    bg: "#F7FFF9",
    surface: "#FFFFFF",
    text: "#065F46",
    textMuted: "#6B7280",
    border: "#E5E7EB",
  },
  {
    id: "medical",
    name: "Medical Green",
    primary: "#10B981",
    primaryDark: "#059669",
    primaryLight: "#D1FAE5",
    accent: "#0EA5E9",
    bg: "#F8FFF8",
    surface: "#FFFFFF",
    text: "#0F172A",
    textMuted: "#64748B",
    border: "#E2E8F0",
  },
  {
    id: "olive",
    name: "Olive Green",
    primary: "#84CC16",
    primaryDark: "#65A30D",
    primaryLight: "#ECFCCB",
    accent: "#A3E635",
    bg: "#FAFCF2",
    surface: "#FFFFFF",
    text: "#1A2E05",
    textMuted: "#6B7280",
    border: "#E5E7EB",
  },
  {
    id: "emerald",
    name: "Emerald Green",
    primary: "#059669",
    primaryDark: "#047857",
    primaryLight: "#A7F3D0",
    accent: "#10B981",
    bg: "#F0FDF4",
    surface: "#FFFFFF",
    text: "#022C22",
    textMuted: "#6B7280",
    border: "#E5E7EB",
  },
  {
    id: "forest",
    name: "Forest Green",
    primary: "#15803D",
    primaryDark: "#166534",
    primaryLight: "#BBF7D0",
    accent: "#22C55E",
    bg: "#F4F8F4",
    surface: "#FFFFFF",
    text: "#052E16",
    textMuted: "#6B7280",
    border: "#E5E7EB",
  },
  {
    id: "sage",
    name: "Sage Green",
    primary: "#9CA3AF",
    primaryDark: "#6B7280",
    primaryLight: "#E5E7EB",
    accent: "#A8B5A8",
    bg: "#F5F7F5",
    surface: "#FFFFFF",
    text: "#1F2937",
    textMuted: "#6B7280",
    border: "#E5E7EB",
  },
  {
    id: "lime",
    name: "Lime Green",
    primary: "#22C55E",
    primaryDark: "#16A34A",
    primaryLight: "#DCFCE7",
    accent: "#4ADE80",
    bg: "#F7FFF7",
    surface: "#FFFFFF",
    text: "#052E16",
    textMuted: "#6B7280",
    border: "#E5E7EB",
  },
  {
    id: "blue",
    name: "Professional Blue",
    primary: "#2563EB",
    primaryDark: "#1D4ED8",
    primaryLight: "#DBEAFE",
    accent: "#3B82F6",
    bg: "#F5F9FF",
    surface: "#FFFFFF",
    text: "#0F172A",
    textMuted: "#64748B",
    border: "#E2E8F0",
  },
  {
    id: "mono",
    name: "Monochrome",
    primary: "#374151",
    primaryDark: "#111827",
    primaryLight: "#F3F4F6",
    accent: "#6B7280",
    bg: "#FAFAFA",
    surface: "#FFFFFF",
    text: "#111827",
    textMuted: "#6B7280",
    border: "#E5E7EB",
  },
];

export const DEFAULT_THEME_ID: ThemeId = "medical";

export function getTheme(id: ThemeId): ThemeColors {
  return THEMES.find((t) => t.id === id) || THEMES[2];
}
